const COLORS=["red","green","yellow","blue"],NAMES=["Ruby","Emerald","Gold","Sapphire"],START=[0,13,26,39];
const PATH=[[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]];
const SAFE=new Set([0,8,13,21,26,34,39,47]);
const HOME={red:[[1,1],[1,4],[4,1],[4,4]],green:[[1,10],[1,13],[4,10],[4,13]],yellow:[[10,1],[10,4],[13,1],[13,4]],blue:[[10,10],[10,13],[13,10],[13,13]]};
const el=id=>document.getElementById(id);
let state={players:4,mode:"local",turn:0,dice:null,rolled:false,game:false,finished:false},players=[];
function setup(){players=Array.from({length:state.players},(_,i)=>({id:i,color:COLORS[i],name:NAMES[i],tokens:[-1,-1,-1,-1],bot:state.mode==="bots"&&i>0}));}
function buildBoard(){const b=el("board");b.innerHTML="";const homes=new Map(Object.entries(HOME).flatMap(([c,a])=>a.map(p=>[p.join(","),c])));
for(let r=0;r<15;r++)for(let c=0;c<15;c++){const cell=document.createElement("div"),key=r+","+c,h=homes.get(key),pi=PATH.findIndex(p=>p[0]===r&&p[1]===c);cell.className="cell";
if(h)cell.classList.add("home-zone","home-"+h);else if(pi>=0){cell.classList.add("track");if(SAFE.has(pi))cell.classList.add("safe");cell.dataset.path=pi;}else if(r>=6&&r<=8&&c>=6&&c<=8)cell.classList.add("center");else cell.classList.add("yard");b.appendChild(cell);}render();}
function canMove(pi,ti){if(!state.game||state.finished||!state.rolled||pi!==state.turn)return false;const p=players[pi],pos=p.tokens[ti],d=state.dice;if(pos>=57)return false;if(pos===-1)return d===6;return pos+d<=57;}
function render(){document.querySelectorAll(".token").forEach(t=>t.remove());players.forEach((p,pi)=>p.tokens.forEach((pos,ti)=>{const t=document.createElement("button");t.className="token";t.title=p.name+" token "+(ti+1);t.style.setProperty("--c","var(--"+p.color+")");let cell;if(pos===-1)cell=HOME[p.color][ti];else if(pos>=57)cell=[7,7];else cell=PATH[(START[pi]+pos)%52];const target=[...el("board").children].find(x=>{const n=[...el("board").children].indexOf(x);return Math.floor(n/15)===cell[0]&&n%15===cell[1];});if(target){target.appendChild(t);if(state.rolled&&pi===state.turn&&canMove(pi,ti))t.classList.add("movable");t.addEventListener("click",()=>move(pi,ti));}}));updatePlayers();}
function updatePlayers(){el("playerList").innerHTML=players.map((p,i)=>'<div class="player-row '+(i===state.turn?"current":"")+'"><div class="avatar '+p.color+'">'+p.name[0]+'</div><div class="player-meta"><div class="player-name">'+p.name+(p.bot?" · Bot":"")+'</div><div class="player-sub">'+(i===state.turn?"Playing now":"Waiting")+'</div></div><div class="token-count">'+p.tokens.filter(x=>x===57).length+'/4</div></div>').join("");el("rollBtn").disabled=!state.game||state.finished||state.rolled||players[state.turn]?.bot;}
function roll(){if(!state.game||state.finished||state.rolled||players[state.turn].bot)return;state.rolled=true;state.dice=Math.floor(Math.random()*6)+1;el("dice").textContent=state.dice;el("dice").classList.add("rolling");setTimeout(()=>el("dice").classList.remove("rolling"),500);const moves=players[state.turn].tokens.map((_,i)=>canMove(state.turn,i)?i:null).filter(x=>x!==null);el("moveHint").textContent=moves.length?"Choose a highlighted token.":"No legal move — next player.";render();if(!moves.length)setTimeout(endTurn,850);}
function move(pi,ti){if(!canMove(pi,ti))return;const p=players[pi],d=state.dice;let pos=p.tokens[ti];p.tokens[ti]=pos===-1?1:pos+d;if(p.tokens[ti]>=57)p.tokens[ti]=57;capture(pi,ti);render();if(p.tokens.every(x=>x===57)){state.finished=true;el("winnerTitle").textContent=p.name+" wins!";el("winnerText").textContent="All four tokens made it home. Great game.";el("winnerModal").classList.remove("hidden");return;}if(d===6){state.rolled=false;state.dice=null;el("dice").textContent="–";el("message").textContent=p.name+" rolled a 6 — roll again!";el("moveHint").textContent="Bonus turn.";render();if(p.bot)setTimeout(bot,700);return;}endTurn();}
function capture(pi,ti){const p=players[pi],pos=p.tokens[ti];if(pos<0||pos>=52)return;const a=(START[pi]+pos)%52;if(SAFE.has(a))return;players.forEach((op,oi)=>{if(oi===pi)return;op.tokens=op.tokens.map(x=>{if(x>=0&&x<52&&(START[oi]+x)%52===a){el("message").textContent=p.name+" sent a "+op.name+" token home!";return -1;}return x;});});}
function endTurn(){state.rolled=false;state.dice=null;state.turn=(state.turn+1)%state.players;el("dice").textContent="–";render();el("turnLabel").textContent=players[state.turn].name+"'s turn";el("message").textContent=players[state.turn].name+", roll the dice.";el("moveHint").textContent=players[state.turn].bot?"Bot is thinking…":"Your move.";if(players[state.turn].bot)setTimeout(bot,650);}
function bot(){if(!state.game||state.finished||!players[state.turn].bot)return;state.rolled=true;state.dice=Math.floor(Math.random()*6)+1;el("dice").textContent=state.dice;render();const moves=players[state.turn].tokens.map((_,i)=>canMove(state.turn,i)?i:null).filter(x=>x!==null);if(moves.length){const choice=moves.sort((a,b)=>players[state.turn].tokens[b]-players[state.turn].tokens[a])[0];setTimeout(()=>move(state.turn,choice),500);}else setTimeout(endTurn,650);}
function start(){state.players=Number(document.querySelector(".segmented .active").dataset.count);state.mode=el("mode").value;state.turn=0;state.dice=null;state.rolled=false;state.game=true;state.finished=false;setup();buildBoard();el("winnerModal").classList.add("hidden");el("turnLabel").textContent=players[0].name+"'s turn";el("message").textContent="Roll the dice to begin.";el("moveHint").textContent="A 6 brings a token onto the track.";}
document.querySelectorAll(".segmented button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".segmented button").forEach(x=>x.classList.remove("active"));b.classList.add("active")}));el("startGame").addEventListener("click",start);el("newGameTop").addEventListener("click",start);el("playAgain").addEventListener("click",start);el("rollBtn").addEventListener("click",roll);buildBoard();updatePlayers();